# Generated by Django 5.2 on 2026-08-14 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0008_venta_ultimos_digitos'),
        ('productos', '0005_alter_historialprecio_precio_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='webpay_amount',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='webpay_buy_order',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='webpay_session_id',
            field=models.CharField(blank=True, max_length=61, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_venta',
            field=models.CharField(choices=[('carrito', 'Carrito'), ('pago_pendiente', 'Pago pendiente'), ('pagado', 'Pagado'), ('pago_error', 'Pago con incidencia')], default='carrito', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='detalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_producto__gt', 0)), name='detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detalle',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='detalle_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='detalle',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_venta__gte', 0)), name='detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='detalle',
            constraint=models.UniqueConstraint(fields=('id_venta', 'producto'), name='detalle_producto_unico_por_venta'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(condition=models.Q(('total_venta__gte', 0)), name='venta_total_no_negativo'),
        ),
    ]
