# Generated by Django 5.2.17 on 2026-08-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0009_venta_webpay_amount_venta_webpay_buy_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='webpay_buy_order',
            field=models.CharField(blank=True, max_length=26, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='webpay_session_id',
            field=models.CharField(blank=True, max_length=61, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='webpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
