# Generated by Django 5.2.17 on 2026-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0010_alter_venta_webpay_buy_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='imagen_producto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
