# Generated by Django 5.2.17 on 2026-10-10 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0012_alter_detalle_producto_alter_venta_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_segundo_despacho', models.PositiveIntegerField(default=5990)),
                ('capacidad_diaria', models.PositiveIntegerField(default=20)),
                ('dias_anticipacion_minima', models.PositiveIntegerField(default=1)),
                ('dias_horizonte', models.PositiveIntegerField(default=30)),
                ('despachos_activos', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FechaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('capacidad_override', models.PositiveIntegerField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=180)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cargo_despacho',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DespachoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha_programada', models.DateField()),
                ('direccion', models.TextField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado para pago'), ('programado', 'Programado'), ('preparacion', 'En preparación'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('cargo', models.PositiveIntegerField(default=0)),
                ('reserva_expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos', to='carro_compras.venta')),
            ],
            options={
                'ordering': ['fecha_programada', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_despacho', to='carro_compras.despachoventa')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_despacho', to='carro_compras.detalle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='despachoventa',
            constraint=models.UniqueConstraint(fields=('venta', 'numero'), name='despacho_numero_unico_por_venta'),
        ),
        migrations.AddConstraint(
            model_name='despachoventa',
            constraint=models.CheckConstraint(condition=models.Q(('numero__in', [1, 2])), name='despacho_numero_valido'),
        ),
        migrations.AddConstraint(
            model_name='detalledespacho',
            constraint=models.UniqueConstraint(fields=('despacho', 'detalle'), name='detalle_unico_por_despacho'),
        ),
        migrations.AddConstraint(
            model_name='detalledespacho',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_despacho_positiva'),
        ),
    ]
