# Generated by Django 5.2.17 on 2026-10-10 00:46

from django.db import migrations
from django.utils import timezone


def migrar_despachos_existentes(apps, schema_editor):
    ConfiguracionDespacho = apps.get_model('carro_compras', 'ConfiguracionDespacho')
    Venta = apps.get_model('carro_compras', 'Venta')
    DespachoVenta = apps.get_model('carro_compras', 'DespachoVenta')
    DetalleDespacho = apps.get_model('carro_compras', 'DetalleDespacho')

    ConfiguracionDespacho.objects.get_or_create(pk=1)
    ventas = Venta.objects.filter(tipo_entrega='despacho', estado_venta='pagado')
    for venta in ventas.iterator():
        if DespachoVenta.objects.filter(venta_id=venta.pk).exists():
            continue
        fecha = venta.fecha_compra.date() if venta.fecha_compra else timezone.localdate()
        despacho = DespachoVenta.objects.create(
            venta_id=venta.pk,
            numero=1,
            fecha_programada=fecha,
            direccion=venta.direccion_despacho or 'Dirección histórica no registrada',
            estado='entregado' if venta.estado_entrega == 'completado' else 'programado',
            cargo=0,
        )
        DetalleDespacho.objects.bulk_create([
            DetalleDespacho(
                despacho_id=despacho.pk,
                detalle_id=detalle.pk,
                cantidad=detalle.cantidad_producto,
            )
            for detalle in venta.detalles.all()
        ])


def no_revertir_despachos(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compras', '0013_configuraciondespacho_fechadespacho_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_despachos_existentes, no_revertir_despachos),
    ]
