# Generated by Django 5.2.17 on 2026-08-21 23:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='PerfilMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maestros/perfiles/')),
                ('descripcion_profesional', models.TextField()),
                ('anos_experiencia', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80)], verbose_name='años de experiencia')),
                ('comuna', models.CharField(max_length=100)),
                ('zonas_trabajo', models.TextField(blank=True, verbose_name='comunas o zonas de trabajo')),
                ('disponible', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('SUSPENDIDO', 'Suspendido')], db_index=True, default='BORRADOR', max_length=12)),
                ('observacion_admin', models.TextField(blank=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('especialidades', models.ManyToManyField(related_name='maestros', to='maestros.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_maestro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de maestro',
                'verbose_name_plural': 'Perfiles de maestros',
                'ordering': ('-fecha_aprobacion', 'usuario__first_name', 'usuario__username'),
            },
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('comuna', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='maestros.especialidad')),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='maestros.perfilmaestro')),
            ],
            options={
                'verbose_name': 'Trabajo realizado',
                'verbose_name_plural': 'Trabajos realizados',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ImagenTrabajoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='maestros/trabajos/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='maestros.trabajorealizado')),
            ],
            options={
                'verbose_name': 'Imagen de trabajo realizado',
                'verbose_name_plural': 'Imágenes de trabajos realizados',
                'ordering': ('creada_en',),
            },
        ),
    ]
