# Generated by Django 5.2.17 on 2026-08-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmaestro',
            name='region',
            field=models.CharField(choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VS', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('LI', "Libertador General Bernardo O'Higgins"), ('ML', 'Maule'), ('NB', 'Ñuble'), ('BI', 'Biobío'), ('AR', 'La Araucanía'), ('LR', 'Los Ríos'), ('LL', 'Los Lagos'), ('AI', 'Aysén del General Carlos Ibáñez del Campo'), ('MA', 'Magallanes y de la Antártica Chilena')], default='RM', max_length=2),
        ),
    ]
