# Generated by Django 5.2.17 on 2026-08-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_especialidades_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajorealizado',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='trabajos_realizados', to='maestros.especialidad'),
        ),
    ]
