# Generated by Django 5.2.17 on 2026-08-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_copiar_especialidades_trabajos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='trabajorealizado',
            name='especialidades',
            field=models.ManyToManyField(related_name='trabajos_realizados', to='maestros.especialidad'),
        ),
    ]
