# Generated by Django 5.2.17 on 2026-08-22 00:52

import maestros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_remove_trabajorealizado_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajorealizado',
            name='fecha',
            field=models.DateField(blank=True, null=True, validators=[maestros.models.validar_fecha_trabajo]),
        ),
    ]
