# Generated by Django 5.2.17 on 2026-08-28 00:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_alter_trabajorealizado_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApelacionMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='PENDIENTE', max_length=10)),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('observacion_admin', models.TextField(blank=True, max_length=2000)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apelacion', to='maestros.perfilmaestro')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apelaciones_maestro_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apelación de maestro',
                'verbose_name_plural': 'Apelaciones de maestros',
                'ordering': ('-enviada_en',),
            },
        ),
    ]
