# Generated by Django 5.2.17 on 2026-08-28 01:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_apelacionmaestro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HISTORICA', 'Observación anterior'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Rechazo'), ('SUSPENSION', 'Suspensión'), ('REACTIVACION', 'Reactivación'), ('APELACION_RECHAZADA', 'Apelación rechazada')], max_length=20)),
                ('texto', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='maestros.perfilmaestro')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_maestro_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación de maestro',
                'verbose_name_plural': 'Observaciones de maestros',
                'ordering': ('-creada_en', '-id'),
            },
        ),
    ]
