# Generated by Django 5.2.17 on 2026-08-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_copiar_observaciones_existentes'),
        ('maestros', '0010_eliminar_maestros_demo'),
    ]

    operations = [
    ]
