# Generated by Django 5.2.17 on 2026-08-29 15:32

import django.db.models.deletion
import maestros.models
import maestros.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_merge_20260828_0147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='tipo_licencia',
            field=models.CharField(choices=[('NINGUNA', 'No requiere licencia'), ('SEC_ELECTRICA', 'SEC eléctrica'), ('SEC_GAS', 'SEC gas')], default='NINGUNA', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Cédula de identidad'), ('ANTECEDENTES', 'Certificado de antecedentes')], max_length=20)),
                ('archivo', models.FileField(storage=maestros.storage.DocumentosPrivadosStorage(), upload_to='maestros/documentos/%Y/%m/', validators=[maestros.models.validar_archivo_documental])),
                ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('observacion_admin', models.TextField(blank=True, max_length=2000)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='maestros.perfilmaestro')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_maestro_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de maestro',
                'verbose_name_plural': 'Documentos de maestros',
                'ordering': ('tipo',),
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo'), name='maestro_documento_tipo_unico')],
            },
        ),
        migrations.CreateModel(
            name='LicenciaMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('SEC_ELECTRICA', 'SEC eléctrica'), ('SEC_GAS', 'SEC gas')], max_length=20)),
                ('clase', models.CharField(choices=[('A', 'Clase A'), ('B', 'Clase B'), ('C', 'Clase C'), ('D', 'Clase D'), ('1', 'Clase 1'), ('2', 'Clase 2'), ('3', 'Clase 3')], max_length=1)),
                ('numero_licencia', models.CharField(max_length=100)),
                ('archivo', models.FileField(storage=maestros.storage.DocumentosPrivadosStorage(), upload_to='maestros/licencias/%Y/%m/', validators=[maestros.models.validar_archivo_documental])),
                ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('observacion_admin', models.TextField(blank=True, max_length=2000)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='maestros.perfilmaestro')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_maestro_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Licencia de maestro',
                'verbose_name_plural': 'Licencias de maestros',
                'ordering': ('tipo_licencia',),
                'constraints': [models.UniqueConstraint(fields=('perfil', 'tipo_licencia'), name='maestro_licencia_tipo_unico')],
            },
        ),
    ]
