# Generated by Django 5.2.17 on 2026-08-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0019_imagenes_individuales_quincalleria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=80)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_inventario', to='productos.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento', 'producto__nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'lote'), name='lote_unico_por_producto')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id_original', models.PositiveBigIntegerField(db_index=True)),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_sku', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('unidad_venta', models.CharField(blank=True, max_length=20)),
                ('precio_unitario', models.PositiveBigIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('inicial', 'Stock inicial'), ('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación')], db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('aplicado', 'Aplicado'), ('anulado', 'Anulado')], db_index=True, default='aplicado', max_length=20)),
                ('origen', models.CharField(choices=[('stock_inicial', 'Stock inicial'), ('reposicion', 'Reposición'), ('venta', 'Venta'), ('ajuste_manual', 'Ajuste manual'), ('edicion_producto', 'Edición de producto'), ('eliminacion_producto', 'Eliminación de producto')], db_index=True, max_length=30)),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0)),
                ('cantidad_movida', models.PositiveIntegerField(default=0)),
                ('cantidad_pendiente', models.PositiveIntegerField(default=0)),
                ('entrada', models.PositiveIntegerField(default=0)),
                ('salida', models.PositiveIntegerField(default=0)),
                ('stock_anterior', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_resultante', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('observacion', models.TextField(blank=True)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='productos.producto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['producto_id_original', '-creado_en'], name='movimientos_product_821afc_idx'), models.Index(fields=['origen', 'estado', '-creado_en'], name='movimientos_origen_5cae79_idx')],
            },
        ),
    ]
