# Generated by Django 5.2.17 on 2026-08-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_registrar_stock_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor_nombre',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('inicial', 'Stock inicial'), ('solicitud', 'En proceso'), ('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('incidencia', 'Incidencia')], db_index=True, max_length=20),
        ),
    ]
