# Generated by Django 5.2.17 on 2026-08-31 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_movimientoinventario_proveedor_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteinventario',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
