# Generated by Django 5.2.17 on 2026-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_historialprecio_precio_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='productos/'),
        ),
    ]
