from decimal import Decimal

from django.db import migrations


SIPA_LATEX_URL = 'https://www.sipa.cl/productos/latex/latex-extracubriente'
PASSOL_DECO_URL = 'https://passol.cl/collections/todo-los-productos-2/products/esmalte-al-agua-deco-colores-empacados-passol'
SIPA_SATINADO_URL = 'https://www.sipa.cl/productos/esmalte-al-agua/esmalte-al-agua-satinado'
SIPA_SEMIBRILLO_URL = 'https://www.sipa.cl/productos/esmalte-al-agua/esmalte-al-agua-semibrillo'
SIPA_FACHADA_URL = 'https://www.sipa.cl/productos/esmalte-al-agua/fachada-extracubriente-hidrorrepelente'
SIPA_PISCINA_URL = 'https://www.sipa.cl/productos/piscinas/pintura-piscina-caucho-clorado'
BOSCH_GSB_URL = 'https://www.bosch-professional.com/cl/es/products/gsb-450-06011B50N0'


def cargar_catalogo_tecnico(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')

    existentes = {
        1: {
            'nombre': 'Martillo carpintero Unitools 16 oz',
            'descripcion': 'Martillo de uña curva con cabeza de acero y mango ergonómico antideslizante para trabajos de carpintería.',
            'marca': 'Unitools',
            'modelo': '16 oz',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Clavar y extraer clavos en trabajos de carpintería, montaje y reparaciones domésticas.',
            'especificaciones': {
                'Tipo': 'Martillo carpintero de uña curva',
                'Peso nominal': '16 oz',
                'Mango': 'Ergonómico antideslizante',
                'Material cabeza': 'Acero',
            },
            'informacion_tecnica_verificada': True,
        },
        2: {
            'nombre': 'Taladro percutor Bauker con cable',
            'descripcion': 'Taladro percutor Bauker con cable, empuñadura auxiliar y selector para perforación con o sin impacto.',
            'marca': 'Bauker',
            'modelo': '',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Perforaciones domésticas en madera, metal y mampostería usando la broca adecuada.',
            'especificaciones': {
                'Tipo': 'Taladro percutor con cable',
                'Empuñadura': 'Auxiliar desmontable',
                'Mandril': 'Con llave',
                'Sentido de giro': 'Reversible',
            },
            'informacion_tecnica_verificada': True,
        },
        3: {
            'nombre': 'Clavo corriente 4 pulgadas (1 kg)',
            'descripcion': 'Paquete de un kilogramo de clavos corrientes de acero de 4 pulgadas para estructuras y trabajos generales en madera.',
            'marca': 'Genérico',
            'modelo': '4 pulgadas',
            'unidad_venta': 'paquete',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'kg',
            'tipo_calculo': 'peso',
            'uso_recomendado': 'Uniones de madera, estructuras temporales, moldajes y trabajos generales de construcción.',
            'especificaciones': {
                'Largo': '4 pulgadas',
                'Material': 'Acero',
                'Contenido': '1 kg',
                'Cabeza': 'Plana',
            },
            'informacion_tecnica_verificada': True,
        },
        4: {
            'nombre': 'Sierra circular Stanley 7-1/4 pulgadas 1600 W',
            'descripcion': 'Sierra circular Stanley de 1600 W con disco de 7-1/4 pulgadas para cortes rectos en madera.',
            'marca': 'Stanley',
            'modelo': '',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Cortes rectos y longitudinales en tableros y piezas de madera, utilizando protección personal.',
            'especificaciones': {
                'Potencia': '1600 W',
                'Diámetro de disco': '7-1/4 pulgadas',
                'Disco mostrado': '24 dientes',
                'Alimentación': 'Eléctrica con cable',
            },
            'informacion_tecnica_verificada': True,
        },
        5: {
            'nombre': 'Sipa Látex Extracubriente blanco 1 galón',
            'descripcion': 'Pintura látex base agua de terminación mate, bajo olor y alto poder cubridor para muros interiores y exteriores.',
            'marca': 'Sipa',
            'modelo': 'Látex Extracubriente',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.785'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('7.926'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 3,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Muros de estuco, hormigón, ladrillo, fibrocemento, pasta muro, yeso y yeso-cartón, en interior o exterior.',
            'especificaciones': {
                'Color': 'Blanco',
                'Base': 'Agua',
                'Terminación': 'Mate',
                'Rendimiento fabricante': '30 a 40 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 30 m² por galón y mano',
                'Capas': '2 a 3 según color y superficie',
                'Aplicación': 'Brocha, rodillo o pistola',
                'Repintado': '3 a 6 horas',
                'Fuente técnica': SIPA_LATEX_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        6: {
            'nombre': 'Combinación para lavaplatos Arizona cromada',
            'descripcion': 'Grifería combinada para lavaplatos con dos mandos, cuello alto y terminación cromada.',
            'marca': 'Arizona',
            'modelo': '',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Instalación sobre lavaplatos con conexiones independientes para agua fría y caliente.',
            'especificaciones': {
                'Tipo': 'Combinación de dos mandos',
                'Terminación': 'Cromada',
                'Montaje': 'Sobre cubierta',
                'Salida': 'Cuello alto',
            },
            'informacion_tecnica_verificada': True,
        },
        7: {
            'nombre': 'Taladro percutor Bosch Professional GSB 450 RE',
            'descripcion': 'Taladro percutor profesional de 450 W, compacto y reversible para perforación en madera, acero y concreto.',
            'marca': 'Bosch Professional',
            'modelo': 'GSB 450 RE',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Perforación con o sin impacto y atornillado en madera, acero, concreto y mampostería.',
            'especificaciones': {
                'Potencia': '450 W',
                'Voltaje': '220 V',
                'Velocidad sin carga': '0 a 3.100 rpm',
                'Impactos': '0 a 49.600 ipm',
                'Mandril': '1 a 10 mm',
                'Peso': '1,2 kg',
                'Perforación madera': '20 mm',
                'Perforación acero/concreto': '10 mm',
                'Fuente técnica': BOSCH_GSB_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        8: {
            'nombre': 'Perno hexagonal métrico de acero',
            'descripcion': 'Perno métrico de cabeza hexagonal para fijaciones desmontables y trabajos generales de montaje.',
            'marca': 'Genérico',
            'modelo': '',
            'unidad_venta': 'unidad',
            'contenido': Decimal('1.000'),
            'unidad_contenido': 'unidad',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Fijaciones mecánicas en estructuras, soportes y montajes; confirmar diámetro y largo requeridos antes de comprar.',
            'especificaciones': {
                'Cabeza': 'Hexagonal',
                'Rosca': 'Métrica parcial',
                'Material': 'Acero',
                'Venta': 'Por unidad',
            },
            'informacion_tecnica_verificada': True,
        },
        9: {
            'nombre': 'Cinta métrica Stanley Pro 8 m / 26 pies',
            'descripcion': 'Huincha de medir retráctil Stanley Pro de ocho metros, con punta magnética y carcasa resistente.',
            'marca': 'Stanley',
            'modelo': '30-088',
            'unidad_venta': 'unidad',
            'contenido': Decimal('8.000'),
            'unidad_contenido': 'm',
            'tipo_calculo': 'unidad',
            'uso_recomendado': 'Mediciones de longitud en construcción, instalación, carpintería y trabajos domésticos.',
            'especificaciones': {
                'Longitud': '8 m / 26 pies',
                'Punta': 'Magnética',
                'Mecanismo': 'Retráctil con bloqueo',
                'Graduación': 'Métrica e imperial',
            },
            'informacion_tecnica_verificada': True,
        },
        10: {
            'nombre': 'Pino dimensionado 2 x 3 pulgadas x 3,2 m',
            'descripcion': 'Pieza de pino dimensionado de 2 x 3 pulgadas y 3,2 metros para estructuras livianas y terminaciones.',
            'marca': 'Genérico',
            'modelo': '2x3 x 3,2 m',
            'unidad_venta': 'unidad',
            'contenido': Decimal('3.200'),
            'unidad_contenido': 'm',
            'tipo_calculo': 'longitud',
            'uso_recomendado': 'Estructuras livianas, entramados, refuerzos, tabiques y trabajos generales en madera.',
            'especificaciones': {
                'Sección nominal': '2 x 3 pulgadas',
                'Largo': '3,2 m',
                'Material': 'Pino',
                'Venta': 'Por pieza',
            },
            'informacion_tecnica_verificada': True,
        },
        11: {
            'nombre': 'Passol Esmalte al Agua Deco blanco mate 1 galón',
            'descripcion': 'Esmalte al agua mate, lavable, hidrorepelente y antihongos para superficies interiores y exteriores.',
            'marca': 'Passol',
            'modelo': 'Línea Deco',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.800'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('9.211'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 3,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Muros, yeso-cartón, fibrocemento, madera preparada, papel mural, concreto, yeso, ladrillo y superficies alcalinas.',
            'especificaciones': {
                'Color': 'Blanco',
                'Base': 'Agua',
                'Terminación': 'Mate',
                'Rendimiento fabricante': '35 a 40 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 35 m² por galón y mano',
                'Capas': '2 a 3 según superficie',
                'Aplicación': 'Brocha, rodillo o pistola',
                'Repintado': '4 a 6 horas',
                'Fuente técnica': PASSOL_DECO_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        12: {
            'nombre': 'Pino dimensionado verde 2 x 2 pulgadas x 3,2 m',
            'descripcion': 'Pieza de pino dimensionado verde de 2 x 2 pulgadas y 3,2 metros para estructuras y trabajos de construcción.',
            'marca': 'Genérico',
            'modelo': '2x2 x 3,2 m',
            'unidad_venta': 'unidad',
            'contenido': Decimal('3.200'),
            'unidad_contenido': 'm',
            'tipo_calculo': 'longitud',
            'uso_recomendado': 'Estructuras livianas, entramados, cierres, refuerzos y trabajos generales en madera.',
            'especificaciones': {
                'Sección nominal': '2 x 2 pulgadas',
                'Largo': '3,2 m',
                'Material': 'Pino dimensionado verde',
                'Venta': 'Por pieza',
            },
            'informacion_tecnica_verificada': True,
        },
    }

    for producto_id, datos in existentes.items():
        Producto.objects.filter(pk=producto_id).update(**datos)

    pinturas_nuevas = {
        13: {
            'nombre': 'Sipa Esmalte al Agua Satinado blanco 1 galón',
            'descripcion': 'Pintura al agua súper lavable y antihongos, de rápido secado y terminación satinada para interiores.',
            'precio': 34990,
            'imagen': 'productos/sipa-esmalte-agua-satinado.webp',
            'stock': 24,
            'categoria': 'Pinturas',
            'activo': True,
            'marca': 'Sipa',
            'modelo': 'Esmalte al Agua Satinado',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.785'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('7.926'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 2,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Muros interiores de concreto, superficies empastadas y superficies previamente selladas.',
            'especificaciones': {
                'Color': 'Blanco', 'Base': 'Agua', 'Terminación': 'Satinado',
                'Rendimiento fabricante': '30 a 40 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 30 m² por galón y mano',
                'Capas': '2 en interior', 'Aplicación': 'Brocha, rodillo o pistola',
                'Repintado': '3 a 6 horas', 'Fuente técnica': SIPA_SATINADO_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        14: {
            'nombre': 'Sipa Esmalte al Agua Semibrillo blanco 1 galón',
            'descripcion': 'Esmalte al agua semibrillo de bajo olor, alta lavabilidad y resistencia UV para interior y exterior.',
            'precio': 37990,
            'imagen': 'productos/sipa-esmalte-agua-semibrillo.webp',
            'stock': 20,
            'categoria': 'Pinturas',
            'activo': True,
            'marca': 'Sipa',
            'modelo': 'Esmalte al Agua Semibrillo',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.785'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('7.926'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 3,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Estuco, hormigón, ladrillo, acero galvanizado y fibrocemento en interior o exterior.',
            'especificaciones': {
                'Color': 'Blanco', 'Base': 'Agua', 'Terminación': 'Semibrillo',
                'Rendimiento fabricante': '30 a 40 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 30 m² por galón y mano',
                'Capas': '2 a 3 según superficie', 'Aplicación': 'Brocha, rodillo o pistola',
                'Repintado': '6 horas', 'Fuente técnica': SIPA_SEMIBRILLO_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        15: {
            'nombre': 'Sipa Fachada Extracubriente Hidrorrepelente 1 galón',
            'descripcion': 'Esmalte al agua hidrorrepelente para fachadas, con protección UV, antihongos y terminación cáscara de huevo.',
            'precio': 42990,
            'imagen': 'productos/sipa-fachada-extracubriente.webp',
            'stock': 18,
            'categoria': 'Pinturas',
            'activo': True,
            'marca': 'Sipa',
            'modelo': 'Fachada Extracubriente Hidrorrepelente',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.785'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('7.926'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 3,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Fachadas exteriores de estuco, hormigón, ladrillo y fibrocemento liso o acanalado.',
            'especificaciones': {
                'Base': 'Agua', 'Terminación': 'Cáscara de huevo', 'Ambiente': 'Exterior',
                'Rendimiento fabricante': '30 a 40 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 30 m² por galón y mano',
                'Capas': '2 a 3 según superficie', 'Aplicación': 'Brocha, rodillo o pistola',
                'Repintado': '6 a 8 horas', 'Fuente técnica': SIPA_FACHADA_URL,
            },
            'informacion_tecnica_verificada': True,
        },
        16: {
            'nombre': 'Sipa Pintura para Piscina azul 1 galón',
            'descripcion': 'Pintura de caucho clorado para piscinas y estanques de hormigón estucado, resistente a sanitizantes.',
            'precio': 44990,
            'imagen': 'productos/sipa-pintura-piscina-caucho-clorado.webp',
            'stock': 12,
            'categoria': 'Pinturas',
            'activo': True,
            'marca': 'Sipa',
            'modelo': 'Pintura Piscina Caucho Clorado',
            'unidad_venta': 'envase',
            'contenido': Decimal('3.785'),
            'unidad_contenido': 'l',
            'tipo_calculo': 'pintura',
            'rendimiento': Decimal('7.133'),
            'unidad_rendimiento': 'm2_l',
            'capas_recomendadas': 3,
            'porcentaje_desperdicio': Decimal('10.00'),
            'uso_recomendado': 'Piscinas y estanques de hormigón previamente impermeabilizados y estucados sin aditivos químicos.',
            'especificaciones': {
                'Color': 'Azul', 'Base': 'Caucho clorado', 'Terminación': 'Lisa y mate',
                'Rendimiento fabricante': '27 a 33 m²/galón/mano',
                'Criterio de cálculo': 'Mínimo declarado: 27 m² por galón y mano',
                'Capas': '3 nueva; 2 repintado', 'Aplicación': 'Brocha o rodillo de pelo corto',
                'Repintado': '8 a 24 horas', 'Fuente técnica': SIPA_PISCINA_URL,
            },
            'informacion_tecnica_verificada': True,
        },
    }

    for producto_id, datos in pinturas_nuevas.items():
        Producto.objects.update_or_create(pk=producto_id, defaults=datos)


class Migration(migrations.Migration):
    dependencies = [('productos', '0007_ficha_tecnica_producto')]

    operations = [
        migrations.RunPython(cargar_catalogo_tecnico, migrations.RunPython.noop),
    ]
