# Generated by Django 5.2.17 on 2026-08-15 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_catalogo_tecnico_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal como #FFFFFF.')]),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.proveedor'),
        ),
        migrations.CreateModel(
            name='SolicitudReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviada', 'Enviada al proveedor'), ('error', 'Error de envío'), ('recibida', 'Mercadería recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('email_destino', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('error_envio', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('recibida_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_reposicion', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='productos.proveedor')),
            ],
            options={
                'ordering': ['-creada_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_al_solicitar', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_reposicion', to='productos.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.solicitudreposicion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'producto'), name='reposicion_producto_unico_por_solicitud')],
            },
        ),
    ]
