from decimal import Decimal

from django.db import migrations


PRODUCTOS = [
    {
        'nombre': 'Tablero pino finger joint 120 x 30 x 1,8 cm',
        'descripcion': 'Tablero de pino encolado, seco y lijado, pensado para repisas, cubiertas y muebles interiores. Se puede cortar, lijar, barnizar o pintar.',
        'precio': 12990,
        'imagen': 'productos/tablero-pino-finger-joint-120x30.png',
        'stock': 35,
        'stock_minimo': 10,
        'marca': 'Genérico SFI',
        'modelo': 'Finger Joint 120x30',
        'unidad_venta': 'unidad',
        'contenido': Decimal('1'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'uso_recomendado': 'Repisas de hasta 120 cm de ancho y 30 cm de fondo, escritorios pequeños y muebles interiores.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas, muebles simples y cubiertas interiores',
            'Dimensiones': '120 x 30 x 1,8 cm',
            'Material': 'Pino finger joint',
            'Preparación': 'Lijar suavemente y aplicar terminación protectora',
        },
    },
    {
        'nombre': 'Escuadras metálicas reforzadas 25 x 20 cm pack 2',
        'descripcion': 'Par de escuadras metálicas para sostener repisas de madera. La capacidad final depende del muro, la fijación y la correcta instalación.',
        'precio': 6990,
        'imagen': 'productos/escuadras-reforzadas-pack-2.png',
        'stock': 50,
        'stock_minimo': 15,
        'marca': 'Genérico SFI',
        'modelo': 'ER-2520',
        'unidad_venta': 'paquete',
        'contenido': Decimal('2'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'uso_recomendado': 'Soporte de repisas de 20 a 30 cm de profundidad en interior.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas y estantes murales',
            'Contenido': '2 escuadras',
            'Dimensiones': '25 x 20 cm',
            'Seguridad': 'Verificar carga admisible del muro y fijaciones antes de instalar',
        },
    },
    {
        'nombre': 'Kit fijación para hormigón y ladrillo pack 10',
        'descripcion': 'Kit de tarugos y tornillos para fijaciones domésticas en hormigón o ladrillo macizo. Requiere perforación del diámetro indicado por el tarugo.',
        'precio': 3990,
        'imagen': 'productos/kit-fijacion-hormigon-pack-10.png',
        'stock': 80,
        'stock_minimo': 20,
        'marca': 'Genérico SFI',
        'modelo': 'FH-10',
        'unidad_venta': 'paquete',
        'contenido': Decimal('10'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['hormigon', 'ladrillo'],
        'uso_recomendado': 'Fijar escuadras y accesorios livianos en hormigón o ladrillo macizo.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas, organizadores y accesorios murales',
            'Contenido': '10 tarugos y 10 tornillos',
            'Muro compatible': 'Hormigón y ladrillo macizo',
            'Advertencia': 'No usar como anclaje estructural ni en ladrillo hueco sin evaluación',
        },
    },
    {
        'nombre': 'Kit anclajes yeso-cartón pack 10',
        'descripcion': 'Anclajes autoperforantes con tornillos para cargas domésticas livianas en placas de yeso-cartón. Para cargas mayores se debe fijar al montante.',
        'precio': 4990,
        'imagen': 'productos/kit-anclajes-yeso-carton-pack-10.png',
        'stock': 70,
        'stock_minimo': 20,
        'marca': 'Genérico SFI',
        'modelo': 'AYC-10',
        'unidad_venta': 'paquete',
        'contenido': Decimal('10'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['yeso_carton'],
        'uso_recomendado': 'Fijaciones livianas sobre placas de yeso-cartón en buen estado.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas livianas, cuadros y organizadores',
            'Contenido': '10 anclajes y 10 tornillos',
            'Muro compatible': 'Yeso-cartón',
            'Advertencia': 'Para cargas relevantes localizar y fijar al montante',
        },
    },
    {
        'nombre': 'Tornillos para madera 4 x 40 mm pack 50',
        'descripcion': 'Tornillos zincados multipropósito para unir madera, escuadras y accesorios en proyectos domésticos.',
        'precio': 4990,
        'imagen': 'productos/tornillos-madera-4x40-pack-50.png',
        'stock': 90,
        'stock_minimo': 25,
        'marca': 'Genérico SFI',
        'modelo': 'TM-4X40',
        'unidad_venta': 'paquete',
        'contenido': Decimal('50'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['madera'],
        'uso_recomendado': 'Armado de muebles simples y unión del tablero a escuadras.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas, cajas, organizadores y muebles simples',
            'Contenido': '50 tornillos',
            'Medida': '4 x 40 mm',
            'Material': 'Acero zincado',
        },
    },
    {
        'nombre': 'Lijas para madera grano 120, 180 y 240 pack 3',
        'descripcion': 'Juego progresivo para preparar y suavizar madera antes de pintar o barnizar.',
        'precio': 2990,
        'imagen': 'productos/lijas-madera-pack-3.png',
        'stock': 60,
        'stock_minimo': 15,
        'marca': 'Genérico SFI',
        'modelo': 'LM-3P',
        'unidad_venta': 'juego',
        'contenido': Decimal('3'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['madera'],
        'uso_recomendado': 'Preparación y terminación manual de superficies de madera.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas, restauración y muebles de madera',
            'Contenido': '1 hoja grano 120, 1 hoja grano 180 y 1 hoja grano 240',
            'Secuencia sugerida': 'Desbaste, suavizado y terminación',
        },
    },
    {
        'nombre': 'Barniz al agua para madera satinado 1 litro',
        'descripcion': 'Terminación transparente al agua para proteger madera interior. Producto complementario opcional para repisas y muebles.',
        'precio': 12990,
        'imagen': 'productos/barniz-agua-satinado-1l.png',
        'stock': 35,
        'stock_minimo': 10,
        'marca': 'Genérico SFI',
        'modelo': 'BA-SAT-1L',
        'color': 'Transparente',
        'ambiente_uso': 'interior',
        'unidad_venta': 'envase',
        'contenido': Decimal('1'),
        'unidad_contenido': 'l',
        'tipo_calculo': 'ninguno',
        'superficies_compatibles': ['madera'],
        'uso_recomendado': 'Protección decorativa de repisas, muebles y objetos de madera en interior.',
        'especificaciones': {
            'Proyectos compatibles': 'Repisas y muebles interiores',
            'Contenido': '1 litro',
            'Terminación': 'Satinada transparente',
            'Preparación': 'Aplicar sobre madera limpia, seca y lijada; seguir instrucciones del envase',
        },
    },
    {
        'nombre': 'Tablero OSB estructural 9,5 mm 122 x 244 cm',
        'descripcion': 'Panel de hojuelas orientadas para revestimientos, cierres, bases y proyectos de carpintería de obra. Debe protegerse de la humedad según su uso.',
        'precio': 19990,
        'imagen': 'productos/tablero-osb-estructural-95mm.png',
        'stock': 30,
        'stock_minimo': 10,
        'marca': 'Genérico SFI',
        'modelo': 'OSB-95-122244',
        'unidad_venta': 'unidad',
        'contenido': Decimal('1'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'uso_recomendado': 'Revestimientos, bases, cierres temporales y muebles de obra.',
        'especificaciones': {
            'Proyectos compatibles': 'Revestimientos, cierres, muebles de obra y bases',
            'Dimensiones': '122 x 244 cm',
            'Espesor': '9,5 mm',
            'Área nominal': '2,98 m² por placa',
        },
    },
    {
        'nombre': 'Placa yeso-cartón estándar 10 mm 120 x 240 cm',
        'descripcion': 'Placa estándar para tabiques y revestimientos interiores secos. No corresponde a una placa resistente a humedad o fuego.',
        'precio': 10990,
        'imagen': 'productos/placa-yeso-carton-st-10mm.png',
        'stock': 45,
        'stock_minimo': 15,
        'marca': 'Genérico SFI',
        'modelo': 'YC-ST-10',
        'ambiente_uso': 'interior',
        'unidad_venta': 'unidad',
        'contenido': Decimal('1'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['yeso_carton'],
        'uso_recomendado': 'Tabiques y revestimientos interiores en ambientes secos.',
        'especificaciones': {
            'Proyectos compatibles': 'Tabiques y revestimientos interiores',
            'Dimensiones': '120 x 240 cm',
            'Espesor': '10 mm',
            'Área nominal': '2,88 m² por placa',
            'Limitación': 'No usar en zonas húmedas o expuestas al exterior',
        },
    },
    {
        'nombre': 'Montante galvanizado 60 x 38 mm x 2,4 m',
        'descripcion': 'Perfil galvanizado tipo C para la estructura de tabiques interiores de yeso-cartón.',
        'precio': 3990,
        'imagen': 'productos/montante-galvanizado-60x38.png',
        'stock': 100,
        'stock_minimo': 25,
        'marca': 'Genérico SFI',
        'modelo': 'MG-6038-24',
        'unidad_venta': 'unidad',
        'contenido': Decimal('2.4'),
        'unidad_contenido': 'm',
        'tipo_calculo': 'longitud',
        'superficies_compatibles': ['metal_galvanizado'],
        'uso_recomendado': 'Estructura vertical de tabiques interiores de yeso-cartón.',
        'especificaciones': {
            'Proyectos compatibles': 'Tabiques y revestimientos interiores',
            'Sección': '60 x 38 mm',
            'Largo': '2,4 m',
            'Material': 'Acero galvanizado',
        },
    },
    {
        'nombre': 'Tornillos yeso-cartón 1 1/4 pulgadas pack 100',
        'descripcion': 'Tornillos fosfatados para fijar placas de yeso-cartón a perfiles metálicos livianos.',
        'precio': 3990,
        'imagen': 'productos/tornillos-yeso-carton-pack-100.png',
        'stock': 90,
        'stock_minimo': 25,
        'marca': 'Genérico SFI',
        'modelo': 'TYC-114-100',
        'unidad_venta': 'paquete',
        'contenido': Decimal('100'),
        'unidad_contenido': 'unidad',
        'tipo_calculo': 'unidad',
        'superficies_compatibles': ['yeso_carton', 'metal_galvanizado'],
        'uso_recomendado': 'Fijación de placas de yeso-cartón a perfiles galvanizados livianos.',
        'especificaciones': {
            'Proyectos compatibles': 'Tabiques y revestimientos interiores',
            'Contenido': '100 tornillos',
            'Largo': '1 1/4 pulgadas',
            'Acabado': 'Fosfatado negro',
        },
    },
    {
        'nombre': 'Cemento uso general saco 25 kg',
        'descripcion': 'Cemento de uso general para morteros y reparaciones domésticas no estructurales, preparado según la dosificación definida para cada trabajo.',
        'precio': 6990,
        'imagen': 'productos/cemento-uso-general-25kg.png',
        'stock': 80,
        'stock_minimo': 20,
        'marca': 'Genérico SFI',
        'modelo': 'CUG-25',
        'unidad_venta': 'saco',
        'contenido': Decimal('25'),
        'unidad_contenido': 'kg',
        'tipo_calculo': 'peso',
        'uso_recomendado': 'Morteros, rellenos y reparaciones domésticas no estructurales siguiendo una dosificación apropiada.',
        'especificaciones': {
            'Proyectos compatibles': 'Morteros, reparaciones y pequeños radieres no estructurales',
            'Contenido': '25 kg',
            'Advertencia': 'La dosificación y resistencia deben definirse según el proyecto; no calcular estructuras sin profesional',
        },
    },
    {
        'nombre': 'Arena seca multiuso saco 25 kg',
        'descripcion': 'Arena seca para preparar mezclas, morteros y rellenos menores. Debe combinarse con los materiales y proporciones adecuados al proyecto.',
        'precio': 2990,
        'imagen': 'productos/arena-seca-multiuso-25kg.png',
        'stock': 70,
        'stock_minimo': 20,
        'marca': 'Genérico SFI',
        'modelo': 'ASM-25',
        'unidad_venta': 'saco',
        'contenido': Decimal('25'),
        'unidad_contenido': 'kg',
        'tipo_calculo': 'peso',
        'uso_recomendado': 'Preparación de morteros y rellenos domésticos de pequeña escala.',
        'especificaciones': {
            'Proyectos compatibles': 'Morteros, reparaciones y rellenos menores',
            'Contenido': '25 kg',
            'Estado': 'Seca',
            'Advertencia': 'Usar una dosificación adecuada para el trabajo y protección personal',
        },
    },
]


def cargar_catalogo(apps, schema_editor):
    Proveedor = apps.get_model('productos', 'Proveedor')
    Producto = apps.get_model('productos', 'Producto')
    proveedor, _ = Proveedor.objects.get_or_create(
        nombre='Proveedor General SFI',
        defaults={
            'nombre_contacto': 'Área comercial',
            'email': 'compras@sfi.local',
            'telefono': '',
            'activo': True,
        },
    )
    for datos in PRODUCTOS:
        defaults = {
            'categoria': 'Construcción',
            'activo': True,
            'proveedor': proveedor,
            'porcentaje_desperdicio': Decimal('10.00'),
            'informacion_tecnica_verificada': True,
            **datos,
        }
        Producto.objects.update_or_create(nombre=datos['nombre'], defaults=defaults)


def eliminar_catalogo(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    Producto.objects.filter(nombre__in=[item['nombre'] for item in PRODUCTOS]).delete()


class Migration(migrations.Migration):
    dependencies = [('productos', '0013_ficha_pintura_avanzada')]

    operations = [migrations.RunPython(cargar_catalogo, eliminar_catalogo)]
