# Generated by Django 5.2.17 on 2026-08-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_catalogo_construccion_para_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
