# Generated by Django 5.2.17 on 2026-08-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_imagenes_individuales_quincalleria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreposicion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviada', 'Envío aprobado'), ('parcial', 'Recepción parcial'), ('error', 'Error de envío'), ('recibida', 'Mercadería recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='RecepcionReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('completa', 'Recepción completa'), ('parcial', 'Recepción parcial'), ('incidencia', 'Recepción con incidencias')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('recibida_en', models.DateTimeField(auto_now_add=True)),
                ('recibida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_reposicion', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='productos.solicitudreposicion')),
            ],
            options={
                'ordering': ['-recibida_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('resultado', models.CharField(choices=[('completo', 'Recibido completo'), ('parcial', 'Recibido parcialmente'), ('no_llego', 'No llegó'), ('danado', 'Llegó dañado'), ('equivocado', 'Producto equivocado'), ('otro', 'Otro problema')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('detalle_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_recepcion', to='productos.detallesolicitudreposicion')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='productos.recepcionreposicion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recepcion', 'detalle_solicitud'), name='recepcion_detalle_solicitud_unico')],
            },
        ),
    ]
