# Generated by Django 5.2.17 on 2026-08-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0022_catalogo_bano_para_asistente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='controla_vencimiento',
            field=models.BooleanField(default=False, help_text='Controla las existencias de este producto por lote y fecha de vencimiento.'),
        ),
    ]
